import '../styles/globals.css'

import { AppWrapper } from '@context/AppContext';
import Head from 'next/head'

function App({ Component, pageProps }) {
  return (
    <AppWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </AppWrapper>
  )
}

export default App
